# Quick syntax check:
# python -c 'import sys, yaml; yaml.dump (yaml.load (sys.stdin), sys.stdout)' <.gitlab-ci.yml

# If things don't seem to work, this can help:
# https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/ci/lint

stages:
  - test
  - deploy

.fedora_install: &fedora_install
  before_script:
    - NM_INSTALL="dnf install -y" ./contrib/fedora/REQUIRED_PACKAGES
    - dnf install -y glibc-langpack-pl ccache clang
    - locale -a
    - contrib/scripts/nm-ci-patch-gtkdoc.sh || true

.fedora_script: &fedora_script
  stage: test
  script:
    - git clean -fdx ; CI=gitlab BUILD_TYPE=autotools CC=gcc   WITH_DOCS=1 contrib/scripts/nm-ci-run.sh
    - mv build/INST/share/gtk-doc/html .git/docs-html
    - git clean -fdx ; CI=gitlab BUILD_TYPE=meson     CC=gcc   WITH_DOCS=1 contrib/scripts/nm-ci-run.sh
    - git clean -fdx ; CI=gitlab BUILD_TYPE=autotools CC=clang WITH_DOCS=0 contrib/scripts/nm-ci-run.sh
    - git clean -fdx ; CI=gitlab BUILD_TYPE=meson     CC=clang WITH_DOCS=0 contrib/scripts/nm-ci-run.sh
    - ./contrib/fedora/rpm/build_clean.sh -g -w crypto_gnutls -w debug -w iwd -w test
    - ./contrib/fedora/rpm/build_clean.sh -g -w crypto_gnutls -w debug -w iwd -w test -w meson
    - mv .git/docs-html .

checkpatch:
  image: fedora:28
  stage: test
  script:
    - dnf install -y git
    - contrib/scripts/checkpatch-feature-branch.sh 2>&1 | tee checkpatch-out.txt
  allow_failure: true
  artifacts:
    when: on_failure
    paths:
      - checkpatch-out.txt

f28_build:
  <<: *fedora_install
  image: fedora:28
  <<: *fedora_script
  artifacts:
    expire_in: 1 day
    paths:
      - docs-html

f_latest_build:
  <<: *fedora_install
  image: fedora:latest
  <<: *fedora_script

f_rawhide_build:
  <<: *fedora_install
  image: fedora:rawhide
  <<: *fedora_script
  allow_failure: true

pages:
  stage: deploy
  dependencies:
    - f28_build
  script:
    - mv docs-html public
  artifacts:
    expire_in: 20 days
    paths:
      - public
  only:
    - master
